### ISSUE TITLE
缺少fis2使用例子

### ISSUE THREAD

**Issue by yanhaijing** [fex-team/fis-parser-babel-6.x#1]

**Comment by hefangshi** [comment]
比起例子，我更推荐大家先使用babel5.x

目前6.x我个人使用上来看，有2个问题
1. preset的加载非常慢，如果你有使用过6.x模块会发现首次加载的时间在5s左右。可能这和我是使用require而不是字符串声明 preset 有关，但是没有深究，因为babel的preset寻找机制目前可配置性很低，还不能达到让 fis 的插件方便的加载的程度。
2. preset 与 plugin 如果在 fis 插件中提供全量包的话，会造成实际体积的 double，因为 preset 实际上是 plugin 的合集。而不提供全量包的话，目前来看，会要求用户手动全局安装或者在项目中本地安装，并不是非常理想，也不太契合 fis 的插件理念。

当然未来 babel 6 肯定会以更大力度想办法去支持，不过不知道 babel 5 和 babel 6 除了在插件机制外，有什么实际性在功能上的差距么？

**Comment by yanhaijing** [comment]
嗯，目前使用的是xiangshouding/fis-parser-babel，我也认为babel太慢了，我在本地连demo都跑不起来，还是等成熟了在用把，npm2下的babel太大了，如果是npm3 会好很多，babel6 这个插件值得好好思考一下，现在目前太乱了，有好多个

**Comment by nimoc** [comment]
https://www.npmjs.com/package/fis-parser-babel-6.x
建议更新 npm包 。我是直接通过 npm 安装的，没有看到 这条建议。首次编译速度太慢，被坑成狗了。

**Comment by yanhaijing** [comment]
@nimojs 你是说升级到npm3？

**Comment by nimoc** [comment]
@yanhaijing 意思说错了，建议在 npm 更新 1.1.0版本，README.md  说明目前不建议使用6.x

**Comment by lcxfs1991** [comment]
一年了，这个居然还没改好。。。

**Comment by yanhaijing** [comment]
^_^
