### ISSUE TITLE
建议例子中的后缀名将.es6修改为.es

### ISSUE THREAD

**Issue by yanhaijing** [fex-team/fis-parser-babel-6.x#2]
为什么我要这么建议呢，因为你是官方例子，请不要误导大家，es6这个名字不好的，为什么呐，babel是准备支持es6 7 8 9 。。。的，而你只写es6，那我的代码里能不能系es7的代码呢，写了es7的代码然后呢，就有歧义了，所以建议修改为es

**Comment by hefangshi** [comment]
babel 官方目前认可的后缀有 es6, es, jsx, js， 但目前社区中更多使用的还是 es6 的后缀，我也有纠结过要不要写 es6.js 这类后缀名，但是不太利于IDE和代码检查工具识别，因此我暂时会保留目前的 es6 这种写法，但是个人更倾向直接写 `js`。

不过这个问题我也在公司内部编码规范的讨论 issue 上提问了，看看能不能在公司内部先以规范的形式达成一致，再修改这里也不迟。

PS: es7的时候还会是 babel6.x 么 :smiley:

**Comment by yanhaijing** [comment]
嗯，直接写js的问题就是不能和目前的js兼容，目前已有的js用babel编译，可能会有问题，所以不许区分，比如使用.es.js 或者.es等，.es的问题就是会绕过公司的代码检查，这样对于将来的代码质量不是好事情，所以最好的写法是些.es.js，这样如果将来不需要编译了可以直接去掉编译流程即可，也不用再讲.es 改为.js了。

PS：babel的版本和es的版本没有关系，我理解你这里babel.6.x 是babel 的版本，babel6也是可以安装es7插件的
